config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  default_url_options :host => "http://localhost:3000" if Rails.env == "development"
  default_url_options :host => "http://agroneto.com" if Rails.env == "production"

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  # mount Thredded::Engine => '/forum'

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "landing#index"

  resources :landing, only: [:index] do
    collection do
      get "select_country"
      post "accept_cookies"
      post "selected_country"
    end
  end
  resources :terms, only: [:index]
  resources :ads, as: "awesome", path: "awesome", only: [:show, :update]

  namespace :blog do
    resources :posts, only: [:index, :show]
  end

  namespace :consults do
    resources :questions, only: [:index, :show, :create, :update] do
      member do
        post "voted"
      end
      resources :answers, only: [:create, :update] do
        member do
          post "voted"
        end
      end
    end

    resources :weather, only: [:index]
  end

  namespace :market do
    resources :publications, only: [:index, :show] do
      collection do
        get "forum"
        get "autocomplete_subcategory_name"
        get "simple_new"
        post "simple_create"
      end
      member do
        post "ask"
        post "mark_as_favorite"
      end
      resources :purchases, only: [:create]
    end

    resources :feedbacks, only: [:new, :create]
  end

  namespace :account do
    resources :users, only: [:show, :edit, :update] do
      collection do
        get "dashboard"
        get "autocomplete_city_name"
        get "unsubscribe_emailing"
      end

      resources :contacts, only: [:index, :show, :create] do
        member do
          post "close"
        end
      end

      resources :notifications, only: [:show]
    end

    resources :feedbacks, only: [:index]
    resources :purchases, only: [:index, :show] do
      member do
        post "mark_as_charged"
        post "mark_as_sent"
        post "mark_as_payed"
      end
    end
    resources :reputations, only: [:index, :new, :update]

    resources :publications, only: [:index, :new, :create, :edit, :update] do
      collection do
        get "favorites" #COMO COMPRADOR
        get "purchases" #COMO COMPRADOR
        get "sales" #COMO VENDEDOR
      end
      member do
        post "make_gold"
        post "change_status"
        post "change_plan"
      end
    end

    resources :questions, only: [:index, :update]

    resources :achivements, only: [:index]
  end

  namespace :api do

    namespace :market do
      namespace :v1 do

        resources :subcategories, only: [:index]

        resources :commodities, only: [:index, :show]
        resources :publications, only: [:new, :create, :show]
      end
    end

    namespace :blog do
      namespace :v1 do
        resources :feed, only: [:index, :new, :create] do
          collection do
            post "upload_images"
          end
        end
        resources :categories, only: [:index]
        resources :posts, only: [:index, :show] do
          collection do
            get "hot"
          end
        end
      end
    end

    namespace :consults do
      namespace :v1 do
        resources :questions, only: [:index, :show, :create, :update] do
          member do
            post "voted"
            post "visited"
          end
          resources :answers, only: [:index, :create, :update] do
            member do
              post "voted"
            end
          end
        end
        resources :weather, only: [:index] do
          collection do
            post "historic"
            post "actual"
            post "forecast"
            post "maps"
          end
        end
      end
    end

    namespace :account do
      namespace :v1 do

        resources :cities, only: [:index]
        resources :feedbacks, only: [:create]
        resources :contacts, only: [:index, :show, :create]
        resources :countries, except: [:index]
        resources :interests, only: [:index]

        resources :sessions, except: [:index, :show, :create, :update, :new, :edit, :destroy] do
          collection do
            post "login"
            post "facebook_login"
            post "register"
          end
        end

        resources :ads, only: [:index] do
          member do
            post "read"
            get "engaged"
          end
        end

        resources :feedbacks, only: [:create]

        resources :notifications, only: [:index] do
          collection do
            get "unread_by_user"
            post "read_all"
          end
          member do
            post "arrived"
            post "read"
          end
        end

        resources :users, except: [:index, :new, :create, :edit, :destroy] do

          collection do
            get "terms"
          end

          member do
            post "confirm_email"
            post "upload_image"
            post "confirm_email"
          end
        end

      end
    end
  end

end

app/controllers/account/publications_controller.rb
class Account::PublicationsController < ApplicationController

  before_action :authenticate_user!, if: lambda { |controller| session[:native_app].nil? }
  acts_as_token_authentication_handler_for User, unless: lambda { |controller| session[:native_app].nil? }

  before_action :load_data


  def index
    @all_publications = current_user.publications.order(created_at: :desc)
    if params[:scope] == "paused"
      @publications = @all_publications.paused
    elsif params[:scope] == "finished"
      @publications = @all_publications.finished
    else
      @publications = @all_publications.actives
    end
  end

  def favorites
    @favorites = current_user.favorites_publications.actives
  end

  def purchases
  end

  def sales
  end

  def new

    if current_user.get_profile_percent < 100
      redirect_to edit_account_user_path(current_user), alert: "¡Para publicar debes completar tu perfil!"
      return
    end

    check_step

    @publication = current_user.publications.new

    if @step == 1

      unless params[:in_need].nil?
        @in_need = true if params[:in_need] == "true"
        @in_need = false if params[:in_need] != "true"
      end

      if !params[:subject].nil?
        @selected_subject = params[:subject]
        @categories = Category.includes(:subcategories).by_subject(params[:subject]).order(name: :asc)
        unless params[:category_id].nil?
          @selected_category = @categories.find_by_id params[:category_id]
          unless @selected_category.nil?
            @subcategories = @selected_category.subcategories.order(name: :asc)
            unless params[:subcategory_id].nil?
              @selected_subcategory = @subcategories.find_by_id params[:subcategory_id]
            else
              if @selected_category.subcategories.count == 1
                @selected_subcategory = @subcategories.first
              end
            end
          end
        end
      elsif !params[:sample_id].nil?
        sample = Publication.find params[:sample_id]
        @selected_subject = sample.subject
        @categories = Category.includes(:subcategories).by_subject(@selected_subject)
        @selected_category = @categories.find_by_id sample.subcategory.category.id
        @subcategories = @selected_category.subcategories
        @selected_subcategory = @subcategories.find_by_id sample.subcategory.id
      end
    end

  end

  def create

    check_step
    @plans = Plan.all.order(priority: :asc)
    @publication = current_user.publications.new params_permit_create
    params[:publication][:step] = @step

    if @publication.save
      @publication.update_attribute :plan_id, @plans.first.id
      redirect_to edit_account_publication_path(@publication, step: 2)
    else
      redirect_to new_account_publication_path(step: 1), alert: "¡Ha ocurrido un error inesperado!"
    end
  end

  def edit
    @step = params[:step].to_i
    @plans = Plan.all.order(priority: :asc)

    @publication = current_user.publications.find params[:id]

    validate_steps

    @publication.publication_images.where(source: nil).delete_all

    if @publication.publication_images.count == 0
      @publication.publication_images.new
    end

    unless @publication.in_need.nil?
      @in_need = @publication.in_need
    end

    unless params[:in_need].nil?
      @in_need = true if params[:in_need] == "true"
      @in_need = false if params[:in_need] != "true"
    end

    unless params[:errors].nil?
      @errors = JSON.parse params[:errors]
    end

    if @step == 2 && @publication.subject == Publication::ANIMALES && !@publication.age.nil?
      @age_selector = @publication.age.to_s.split(" ")
      if @age_selector.count > 0
        @age_selector = @age_selector[1]
      end
      @publication.age = @publication.age.to_s.gsub(" ", "").gsub("Año(s)", "").gsub("Mes(es)", "")
    end

    if !@publication.status.nil? && @publication.status > 0
      @selected_subject = @publication.subject
      @categories = Category.includes(:subcategories).by_subject(@publication.subject).order(name: :asc)
      @selected_category = @categories.find_by_id @publication.subcategory.category_id
      @subcategories = @selected_category.subcategories.order(name: :asc)
      @selected_subcategory = @subcategories.find_by_id @publication.subcategory_id

      if !params[:subject].nil?
        @selected_subject = params[:subject]
        @categories = Category.includes(:subcategories).by_subject(params[:subject]).order(name: :asc)
        unless params[:category_id].nil?
          @selected_category = @categories.find_by_id params[:category_id]
          unless @selected_category.nil?
            @subcategories = @selected_category.subcategories.order(name: :asc)
            unless params[:subcategory_id].nil?
              @selected_subcategory = @subcategories.find_by_id params[:subcategory_id]
            else
              if @selected_category.subcategories.count == 1
                @selected_subcategory = @subcategories.first
              end
            end
          end
        end
      end

      #@plans = @plans.where("priority > ?", @publication.plan.priority)
    end

    check_step
  end

  def update

    check_step

    @publication = current_user.publications.find params[:id]
    params[:publication][:step] = @step

    #Capitalización de campos de texto para uniformidad
    params[:publication][:title] = params[:publication][:title].titleize unless params[:publication][:title].nil?
    # params[:publication][:description] = params[:publication][:description].capitalize unless params[:publication][:description].nil?
    params[:publication][:warranty_description] = params[:publication][:warranty_description].capitalize unless params[:publication][:warranty_description].nil?

    if @publication.update params_permit_update
      @publication.update_attribute(:age, "#{params[:publication][:age]} #{params_permit_create_none[:age_selector]}") if @step == 2 && @publication.subject == Publication::ANIMALES

      if @step == 2
        if @publication.publication_images.where.not(source: nil).count == 0
          redirect_to edit_account_publication_path(@publication, step: @step), alert: "Debes ingresar al menos 1 imagen."
          return
        end
      end

      @publication.update_attribute(:end_date, Time.now + 1.month) if @step == 3 && @publication.end_date.nil?

      if @step +1 < 4
        redirect_to edit_account_publication_path(@publication, step: @step + 1)
      else
        if @publication.status == 0 || @publication.status.nil?
          Notification.create_and_send(Notification::PUBLICATION_CREATED, @publication, current_user)
        end
        @publication.update_attribute(:status, 1) if @step == 3
        redirect_to edit_account_publication_path(@publication, step: @step + 1), notice: "Tu publicación ya se encuentra al aire. Usa tus puntos para más exposición y tiempo ilimitado para tu publicación."
      end
    else

      @publication.title = params[:publication][:title].titleize unless params[:publication][:title].nil?
      # @publication.description = params[:publication][:description].capitalize unless params[:publication][:description].nil?
      @publication.kind = params[:publication][:kind] unless params[:publication][:kind].nil?
      @publication.units = params[:publication][:units] unless params[:publication][:units].nil?
      @publication.price = params[:publication][:price] unless params[:publication][:price].nil?
      @publication.city_id = params[:publication][:city_id] unless params[:publication][:city_id].nil?
      @publication.address = params[:publication][:address] unless params[:publication][:address].nil?
      @publication.year = params[:publication][:year] unless params[:publication][:year].nil?
      @publication.year = params[:publication][:year] unless params[:publication][:year].nil?
      @publication.brand = params[:publication][:brand] unless params[:publication][:brand].nil?
      @publication.km = params[:publication][:km] unless params[:publication][:km].nil?
      @publication.model = params[:publication][:model] unless params[:publication][:model].nil?
      @publication.transmission = params[:publication][:transmission] unless params[:publication][:transmission].nil?
      @publication.cylinder = params[:publication][:cylinder] unless params[:publication][:cylinder].nil?
      @publication.color = params[:publication][:color] unless params[:publication][:color].nil?
      @publication.fuel_type = params[:publication][:fuel_type] unless params[:publication][:fuel_type].nil?
      @publication.shipping = params[:publication][:shipping] unless params[:publication][:shipping].nil?
      @publication.pickup = params[:publication][:pickup] unless params[:publication][:pickup].nil?
      @publication.shipping_price = params[:publication][:shipping_price] unless params[:publication][:shipping_price].nil?
      if @step == 2 && @publication.subject == Publication::ANIMALES
        @publication.age = "#{params[:publication][:age]} #{params_permit_create_none[:age_selector]}" unless params[:publication][:age].nil?
      end
      @publication.willing_to_move = params[:publication][:willing_to_move] unless params[:publication][:willing_to_move].nil?
      @publication.to_agree = params[:publication][:to_agree] unless params[:publication][:to_agree].nil?
      @publication.with_ac = params[:publication][:with_ac] unless params[:publication][:with_ac].nil?
      @publication.uniq_owner = params[:publication][:uniq_owner] unless params[:publication][:uniq_owner].nil?
      @publication.for_adoption = params[:publication][:for_adoption] unless params[:publication][:for_adoption].nil?
      @publication.for_adoption = params[:publication][:number] unless params[:publication][:number].nil?
      @publication.for_adoption = params[:publication][:total_mtr] unless params[:publication][:total_mtr].nil?

app/controllers/api/market/v1/publications_controller.rb
class Api::Market::V1::PublicationsController < Api::ApiNsController

  layout "layouts/application_api"

  def show
    @publication = Publication.ready.find params[:id]
    @user = @publication.user
    @reputation = @publication.user.get_reputation_data
    @publication.update_attribute :visits_count, @publication.visits_count + 1
  end

end

app/views/market/publications/show/_description.html.erb
<div class="row" style="margin-top: 40px;">
  <div class="col-md-8 col-md-offset-2">
    <h2 class="green text-center">
      Descripción de la publicación
    </h2>
    <hr>
  </div>
  <div class="col-md-8 col-md-offset-2">
    <%= raw @publication.description %>
  </div>
</div>

app/views/market/publications/show/_images.html.erb
<div id="carousel-publication" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @publication.publication_images.each_with_index do |image, i| %>
    <li data-target="#carousel-publication" data-slide-to="<%= i%>" class="<%= i == 0 ? 'active' : '' %>"></li>
    <% end %>
    <% if !@publication.video.nil? && @publication.video != "" %>
      <li data-target="#carousel-publication" data-slide-to="<%= @publication.publication_images.count%>"></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @publication.publication_images.each_with_index do |image, i| %>
    <div class="item <%= i == 0 ? 'active' : '' %>">
      <%= image_tag image.source.original.url, class: "img-responsive" %>
    </div>
    <% end %>
    <% if !@publication.video.nil? && @publication.video != "" %>
    <div class="item">
      <div class="embed-responsive embed-responsive-16by9" id="video-source">
        <!-- Aqui se pega el video por JS -->
      </div>
    </div>
    <script type="text/javascript">
    loadYoutubeVideo("#video-source", "<%= @publication.video %>");
    </script>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-publication" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-publication" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/market/publications/show/_info_animals.html.erb
<% if @publication.subject == Publication::ANIMALES  %>
<div class="row" style="margin-top: 40px;">
  <div class="col-md-8 col-md-offset-2 text-center">
    <h2 class="green">
      ¿Cómo comprar?
    </h2>
    <p>
      <i class="fa fa-list"></i>
      Los siguientes pasos aseguran una transacción exitosa.
    </p>
    <hr>
  </div>
  <div class="col-md-12">
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 1: Contactar
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        Lee la publicación y contacta al propietario del o los animales, has todas las preguntas necesarias, un buen vendedor responde en un periodo corto de tiempo.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 2: Informar
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        Asegúrate de conocer el registro del animal, si el animal no cuenta con el mismo, preguntale al vendedor los orígenes de este, y comprueba que el animal cuente con todas las vacunas necesarias, y que su estado de salud sea óptimo.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 3: Documentación
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        En el caso de caninos y felinos el vendedor debe facilitar siempre los documentos necesarios: factura, certificado veterinario actualizado y  si el animal es de raza su correspondiente pedigree.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 4: Buen vendedor
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        Para una correcta socialización, los cachorros, tanto caninos como felinos, deben permanecer con su madre y hermanos hasta una edad determinada, dependiendo de la especie.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 5: Buen criador
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        Asegúrate del aspecto y estado de los animales ¿Se encuentran en un entorno apropiado, limpio, con el espacio idóneo según su edad.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 6: Precio
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        Desconfía de ofertas que están muy por debajo del valor real
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          ¡Recuerda!
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        AgroNeto no tiene ningún animal bajo su cargo, es solo una herramienta informativa.
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/market/publications/show/_info_inmuebles.html.erb
<% if @publication.subject == Publication::INMUEBLES || @publication.subject == Publication::VEHICULOS %>
<% name = "inmueble y/o terreno" if @publication.subject == Publication::INMUEBLES %>
<% name = "vehículo y/o remolque" if @publication.subject == Publication::VEHICULOS %>
<div class="row" style="margin-top: 40px;">
  <div class="col-md-8 col-md-offset-2 text-center">
    <h2 class="green">
      ¿Cómo comprar?
    </h2>
    <p>
      <i class="fa fa-list"></i>
      Los siguientes pasos aseguran una transacción exitosa.
    </p>
    <hr>
  </div>
  <div class="col-md-12">
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 1: Contactar
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        Lee la publicación y contacta al vendedor, pacta una visita para conocer el <%= name%>, un buen vendedor responde en un periodo corto de tiempo.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 2: Visitar
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        No pagues sin verificar personalmente la documentación y el estado del <%= name%>.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 3: Investigar
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        Cuídate si mencionan ventas rápidas por mudanza y desconfía de ofertas muy por debajo del precio del mercado.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 4: Pagar
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        No uses servicios de pago anónimos (por ej: Western Union), ni envíes dinero al exterior.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          ¡Recuerda!
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        AgroNeto no tiene <%= name%> bajo su custodia, es solo una herramienta informativa.
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/market/publications/show/_info_services.html.erb
<% if @publication.subject == Publication::SERVICIOS %>
<div class="row" style="margin-top: 40px;">
  <div class="col-md-8 col-md-offset-2 text-center">
    <h2 class="green">
      ¿Cómo comprar?
    </h2>
    <p>
      <i class="fa fa-list"></i>
      Los siguientes pasos aseguran una transacción exitosa.
    </p>
    <hr>
  </div>
  <div class="col-md-12">
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 1: Contactar
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        Lee la publicación y contacta al proveedor del servicio, no olvides preguntar por su experiencia y experticia, un buen vendedor responde en un periodo corto de tiempo.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 2: Informar
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        Da solo la información necesaria, que necesitas hacer, cuando lo necesitar hacer y donde lo necesitas hacer.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          Paso 3: Pagar
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        No uses servicios de pago anónimos (por ej: Western Union), ni envíes dinero al exterior.
      </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-2 col-xs-4 text-right">
        <h4 class="green">
          ¡Recuerda!
        </h4>
      </div>
      <div class="col-md-8 col-xs-8" style="border-left: 1px solid #f2f2f2">
        AgroNeto no tiene ningún proveedor de servicio bajo su cargo, es solo una herramienta informativa.
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/market/publications/show/_other_publications.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2 class="green text-center">
      Publicaciones interesantes
    </h2>
  </div>
</div>

app/views/market/publications/show/_questions.html.erb
<% if publication.subject == Publication::PRODUCTOS %>
<div class="row" style="margin-top: 40px;">
  <div class="col-md-8 col-md-offset-2">
    <h2 class="green text-center">
      Preguntas al vendedor
    </h2>
    <hr>
  </div>
  <div class="col-md-8 col-md-offset-2">
    <table class="table">
      <tr>
        <td class="alert alert-info">
          <% if user_signed_in? %>
            <%= nested_form_for [:market, publication], url: ask_market_publication_path(id: publication.id), html: {method: :post} do |f| %>
            <!-- <i class="fa fa-comment"></i> -->
            <textarea class="form-control" placeholder="Escribe una pregunta" height=100 name="question"></textarea>
            <br>
            <button type="submit" class="btn btn-primary">
              Preguntar
            </button>
            <small style="margin-left: 20px;">No ingreses datos de contacto, no uses lenguaje vulgar ni ofertes o preguntes por otro artículo.</small>
            <% end %>
          <% else %>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#subscribe-modal">
            Preguntar
          </button>
          <% end %>
        </td>
      </tr>
      <% if publication.publication_questions.count == 0 %>
      <tr>
        <td>
          <div class="alert alert-warning" style="margin-top: 20px;">
            Esta publicación aún no tiene preguntas
          </div>
        </td>
      </tr>
      <% end %>
      <% publication.publication_questions.order(created_at: :desc).each do |question| %>
      <tr>
        <td>
          <i class="fa fa-comment"></i> <%= question.question %>
          <% unless question.answer.nil? %>
          <br>
          <i class="fa fa-comments" style="margin-left: 40px;"></i> <%= question.answer %>
          <hr>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>
<% end %>

app/views/market/publications/show/_seller_info.html.erb
<% #if @publication.subject == Publication::PRODUCTOS %>
<div class="row" style="margin-top: 20px;">
  <div class="col-md-8 col-md-offset-2 text-center">
    <h2 class="green">
      Información sobre el vendedor
    </h2>
    <p>
      <i class="fa fa-map-marker"></i>
      <%= @publication.user.city.name %> - <%= @publication.user.city.department.name %>
    </p>
    <% if params[:native_app].blank? %>
      <%= link_to "Ver Perfil", account_user_path(@publication.user), class: "btn btn-secondary btn-lg" %>
    <% end %>
    <hr>
  </div>
  <div class="col-md-12">
    <div class="row">
      <div class="col-xs-12 col-md-2 text-right">
        <h4 class="green">
          Reputación cómo vendedor
        </h4>
      </div>
      <div class="col-md-8 col-xs-12" style="border-left: 1px solid #f2f2f2">
        <% if @reputation[:sells_count] >= 8 %>
        <table>
          <tr>
            <td style="font-size: 25px; padding: 10px;">
              <%= @reputation[:percent] %>%
            </td>
            <td style="border-right: 1px solid #f2f2f2; padding: 10px;">
              De sus compradores lo recomiendan
            </td>
            <td style="font-size: 25px; padding: 10px;">
              <%= @reputation[:sells_count] %>
            </td>
            <td style="border-right: 1px solid #f2f2f2; padding: 10px;">
              Ventas concretadas
            </td>
            <td style="padding: 10px;">
              <b>
                <%= time_ago_in_words @user.created_at %>
              </b><br>
              Vendiendo en AgroNeto
            </td>
          </tr>
        </table>
        <% else %>
        <div class="alert alert-warning">
          <div class="row">
            <div class="col-md-2">
              <i class="fa fa-thumbs-up fa-4x"></i>
            </div>
            <div class="col-md-10">
              Compra a este nuevo vendedor y recibe el doble de PuntosAgro.
              <br>
              <b>AgroNeto</b> apoya a los nuevos vendedores.
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%# end %>