config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  default_url_options :host => "http://localhost:3000" if Rails.env == "development"
  default_url_options :host => "http://agroneto.com" if Rails.env == "production"

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  # mount Thredded::Engine => '/forum'

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "landing#index"

  resources :landing, only: [:index] do
    collection do
      get "select_country"
      post "accept_cookies"
      post "selected_country"
    end
  end
  resources :terms, only: [:index]
  resources :ads, as: "awesome", path: "awesome", only: [:show, :update]

  namespace :blog do
    resources :posts, only: [:index, :show]
  end

  namespace :consults do
    resources :questions, only: [:index, :show, :create, :update] do
      member do
        post "voted"
      end
      resources :answers, only: [:create, :update] do
        member do
          post "voted"
        end
      end
    end

    resources :weather, only: [:index]
  end

  namespace :market do
    resources :publications, only: [:index, :show] do
      collection do
        get "forum"
        get "autocomplete_subcategory_name"
        get "simple_new"
        post "simple_create"
      end
      member do
        post "ask"
        post "mark_as_favorite"
      end
      resources :purchases, only: [:create]
    end

    resources :feedbacks, only: [:new, :create]
  end

  namespace :account do
    resources :users, only: [:show, :edit, :update] do
      collection do
        get "dashboard"
        get "autocomplete_city_name"
        get "unsubscribe_emailing"
      end

      resources :contacts, only: [:index, :show, :create] do
        member do
          post "close"
        end
      end

      resources :notifications, only: [:show]
    end

    resources :feedbacks, only: [:index]
    resources :purchases, only: [:index, :show] do
      member do
        post "mark_as_charged"
        post "mark_as_sent"
        post "mark_as_payed"
      end
    end
    resources :reputations, only: [:index, :new, :update]

    resources :publications, only: [:index, :new, :create, :edit, :update] do
      collection do
        get "favorites" #COMO COMPRADOR
        get "purchases" #COMO COMPRADOR
        get "sales" #COMO VENDEDOR
      end
      member do
        post "make_gold"
        post "change_status"
        post "change_plan"
      end
    end

    resources :questions, only: [:index, :update]

    resources :achivements, only: [:index]
  end

  namespace :api do

    namespace :market do
      namespace :v1 do

        resources :subcategories, only: [:index]

        resources :commodities, only: [:index, :show]
        resources :publications, only: [:new, :create, :show]
      end
    end

    namespace :blog do
      namespace :v1 do
        resources :feed, only: [:index, :new, :create] do
          collection do
            post "upload_images"
          end
        end
        resources :categories, only: [:index]
        resources :posts, only: [:index, :show] do
          collection do
            get "hot"
          end
        end
      end
    end

    namespace :consults do
      namespace :v1 do
        resources :questions, only: [:index, :show, :create, :update] do
          member do
            post "voted"
            post "visited"
          end
          resources :answers, only: [:index, :create, :update] do
            member do
              post "voted"
            end
          end
        end
        resources :weather, only: [:index] do
          collection do
            post "historic"
            post "actual"
            post "forecast"
            post "maps"
          end
        end
      end
    end

    namespace :account do
      namespace :v1 do

        resources :cities, only: [:index]
        resources :feedbacks, only: [:create]
        resources :contacts, only: [:index, :show, :create]
        resources :countries, except: [:index]
        resources :interests, only: [:index]

        resources :sessions, except: [:index, :show, :create, :update, :new, :edit, :destroy] do
          collection do
            post "login"
            post "facebook_login"
            post "register"
          end
        end

        resources :ads, only: [:index] do
          member do
            post "read"
            get "engaged"
          end
        end

        resources :feedbacks, only: [:create]

        resources :notifications, only: [:index] do
          collection do
            get "unread_by_user"
            post "read_all"
          end
          member do
            post "arrived"
            post "read"
          end
        end

        resources :users, except: [:index, :new, :create, :edit, :destroy] do

          collection do
            get "terms"
          end

          member do
            post "confirm_email"
            post "upload_image"
            post "confirm_email"
          end
        end

      end
    end
  end

end

app/controllers/account/questions_controller.rb
class Account::QuestionsController < ApplicationController

  before_action :authenticate_user!, if: lambda { |controller| session[:native_app].nil? }
  acts_as_token_authentication_handler_for User, unless: lambda { |controller| session[:native_app].nil? }
  
  before_action :load_data

  def index
    @questions = PublicationQuestion.pending(current_user).order(created_at: :asc)
  end

  def update
    @question = PublicationQuestion.pending(current_user).find params[:id]
    if params[:publication_question][:answer].nil? || params[:publication_question][:answer] == ""
      redirect_to account_questions_path, alert: "Tu respuesta no puede estar en blanco"
    else
      @question.update(answer: params[:publication_question][:answer], answer_time: Time.now)
      Notification.create_and_send(Notification::QUESTION_ANSWERED, @question, question.user)
      redirect_to account_questions_path, notice: "Respuesta enviada al comprador"
    end
  end

  def load_data
    @not_show_main_banner = true
  end

end

app/controllers/api/consults/v1/answers_controller.rb
class Api::Consults::V1::AnswersController < Api::ApiNsController

  acts_as_token_authentication_handler_for User, only: [:index, :show, :create, :update, :voted]

  before_action :get_question

  def index
    @answers = @question.answers.hot
  end

  def show
    @answers = @question.answers.find params[:id]
  end

  def create
    answer = @question.answers.create params_permit
    answer.points = 0
    answer.user_id = current_user.id

    if answer.save
      Notification.create_and_send(Notification::CONSULT_ANSWER, answer, answer.question.user)
      @answer = answer
      render "index"
    else
      render status: 411, json: {message: "¡No pudimos enviar tu pregunta!", errors: answer.errors.full_messages.to_sentence}
    end
  end

  def update
    answer = @question.answers.find params_permit

    if answer.update params[:answer]
      render status: 200, json: {message: "¡Tu pregunta ha sido actualizada correctamente!"}
    else
      render status: 411, json: {message: "¡No pudimos actualizar tu pregunta!", errors: answer.errors.full_messages.to_sentence}
    end
  end

  def voted
    answer = @question.answers.find params[:id]

    if current_user.has_voted_answer?(answer)
      if current_user.has_voted_answer_as_value?(answer, params[:value])

        render status: 411, json: {message: "¡Ya has calificado esta respuesta!"}
        return
      end
      vote = current_user.get_voted_answer(answer)
      vote.update_attribute :points, params[:value]
      render status: 200, json: {message: "¡Gracias por calificar la respuesta!"}
      return
    end

    if params[:value].to_i > 0
      answer.update_attribute :points, answer.points + 1
      answer.user_consult_answer_votes.create user_id: current_user.id, points: 1
    else
      answer.update_attribute :points, answer.points - 1
      answer.user_consult_answer_votes.create user_id: current_user.id, points: -1
    end

    render status: 200, json: {message: "¡Gracias por calificar la respuesta!"}
  end

  def params_permit
    params.require(:answer).permit(:text, :user_id, consult_answer_images_attributes: [:source, :id, :_destroy])
  end

  private

  def get_question
    @question = ConsultQuestion.find params[:question_id]
  end

end

app/controllers/api/consults/v1/questions_controller.rb
class Api::Consults::V1::QuestionsController < Api::ApiNsController

  acts_as_token_authentication_handler_for User, only: [:create, :update, :voted, :visited]

  def index
    if params[:scope] == "recents"
      @questions = ConsultQuestion.recents
    elsif params[:scope] == "hot"
      @questions = ConsultQuestion.hot
    else
      @questions = ConsultQuestion.all
    end

    unless params[:category_id]
      @questions = @questions.by_categories(params[:category_id])
    end
    page = params[:page]
    if page.nil?
      page = 1
    end
    @questions = @questions.page(page).per(25)
  end

  def show
    @questions = ConsultQuestion.find params[:id]

    render "index"
  end

  def create
    question = current_user.consult_questions.new params_permit
    question.points = 0
    question.visits_count = 0
    if question.save
      User.consult_managers.each do |user|
        Notification.create_and_send(Notification::CONSULT_MANAGER, question, user)
      end
      @questions = question
      render "index"
    else
      render status: 411, json: {message: "No se pudo crear tu pregunta", errors: question.errors.full_messages.to_sentence}
    end
  end

  def update
    question = current_user.consult_questions.find params[:id]

    if question.update params[:question]
      render status: 200, json: {message: "¡Pregunta actualizada correctamente!"}
    else
      render status: 411, json: {message: "No se pudo actualizar tu pregunta", errors: question.errors.full_messages.to_sentence}
    end
  end

  def voted
    question = ConsultQuestion.find params[:id]

    if current_user.has_voted_question?(question)
      if current_user.has_voted_question_as_value?(question, params[:value])
        render status: 411, json: {message: "¡Ya has calificado esta pregunta!"}
        return
      end
      vote = current_user.get_voted_question(question)
      vote.update_attribute :points, params[:value]
      render status: 200, json: {message: "¡Gracias por calificar la pregunta!"}
      return
    end

    if params[:value].to_i > 0
      question.update_attribute :points, question.points + 1
      question.user_consult_question_votes.create user_id: current_user.id, points: 1
    else
      question.update_attribute :points, question.points - 1
      question.user_consult_question_votes.create user_id: current_user.id, points: -1
    end

    render status: 200, json: {message: "¡Gracias por calificar la pregunta!"}
  end

  def visited
    question = ConsultQuestion.find params[:id]
    question.update_attribute :visits_count, question.visits_count + 1

    question.user_consult_question_visits.create user_id: current_user.id

    render status: 200, json: {message: "Pregunta visitada"}
  end

  private

  def params_permit
    params.require(:question).permit(:text, consult_question_images_attributes: [:source, :id, :_destroy])
  end

end

app/controllers/api/consults/v1/weather_controller.rb
class Api::Consults::V1::WeatherController < Api::ApiNsController

  # acts_as_token_authentication_handler_for User, only: [:create, :update, :voted, :visited]
  layout "layouts/application_api"

  def index
    @country = Country.find_by_id params[:country_id]
  end

  def historic
  end

  def actual
  end

  def forecast
  end

  def maps
  end

end

app/controllers/consults/answers_controller.rb
class Consults::AnswersController < ApplicationController

  before_action :authenticate_user!

  before_action :get_question

  def create

    unless @question.answers.find_by_user_id(current_user.id).nil?
      redirect_to params[:redirect_to], notice: "¡Ya has dado respuesta a esta pregunta!"
      return
    end

    answer = @question.answers.create params_permit
    answer.points = 0
    answer.user_id = current_user.id

    if answer.save
      Notification.create_and_send(Notification::CONSULT_ANSWER, answer, answer.question.user)
      redirect_to params[:redirect_to], notice: "Respuesta enviada correctamente, gracias por responder!"
    else
      redirect_to params[:redirect_to], alert: answer.errors.full_messages.to_sentence
    end
  end

  def voted
    answer = @question.answers.find params[:id]

    if current_user.has_voted_answer?(answer)
      if current_user.has_voted_answer_as_value?(answer, params[:value])
        redirect_to params[:redirect_to], alert: "¡Ya has calificado esta respuesta!"
        return
      end

      if params[:value].to_i > 0
        current_user.update_attribute :likes, current_user.likes + 1
        current_user.update_attribute :dislike, current_user.likes - 1
      else
        current_user.update_attribute :likes, current_user.likes - 1
        current_user.update_attribute :dislike, current_user.likes + 1
      end

      vote = current_user.get_voted_answer(answer)
      vote.update_attribute :points, params[:value]
      redirect_to params[:redirect_to], notice: "¡Gracias por calificar la respuesta!"
      return
    end

    if params[:value].to_i > 0
      current_user.update_attribute :likes, current_user.likes + 1
      answer.update_attribute :points, answer.points + 1
      answer.user_consult_answer_votes.create user_id: current_user.id, points: 1
    else
      current_user.update_attribute :dislikes, current_user.likes + 1
      answer.update_attribute :points, answer.points - 1
      answer.user_consult_answer_votes.create user_id: current_user.id, points: -1
    end

    redirect_to params[:redirect_to], notice: "¡Gracias por calificar la respuesta!"
  end

  private

  def params_permit
    params.require(:answer).permit(:text, :user_id, consult_answer_images_attributes: [:source, :id, :_destroy])
  end

  def get_question
    @question = ConsultQuestion.find params[:question_id]
  end


end

app/controllers/consults/questions_controller.rb
class Consults::QuestionsController < ApplicationController

  before_action :authenticate_user!, only: [:create, :update, :voted]
  before_action :load_data

  def index
    if params[:scope] == "recents"
      @questions = ConsultQuestion.recents
    elsif params[:scope] == "hot"
      @questions = ConsultQuestion.hot
    else
      @questions = ConsultQuestion.all
    end

    unless params[:category_id].nil?
      @questions = @questions.by_categories(params[:category_id])
    end
    page = params[:page]
    if page.nil?
      page = 1
    end
    @questions = @questions.page(page).per(25)
  end

  def show
    @question = ConsultQuestion.find params[:id]
  end

  def create
    question = current_user.consult_questions.new params_permit
    question.points = 0
    question.visits_count = 0
    if question.save
      User.consult_managers.each do |user|
        Notification.create_and_send(Notification::CONSULT_MANAGER, question, user)
      end
      redirect_to params[:redirect_to], notice: "¡Pregunta creada correctamente, gracias por preguntar!"
    else
      redirect_to params[:redirect_to], alert: question.errors.full_messages.to_sentence
    end
  end

  def update
    question = current_user.consult_questions.find params[:id]

    if question.update params_permit
      redirect_to params[:redirect_to], notice: "¡Pregunta actualizada correctamente!"
    else
      redirect_to params[:redirect_to], alert: question.errors.full_messages.to_sentence
    end
  end

  def voted
    question = ConsultQuestion.find params[:id]

    if current_user.has_voted_question?(question)
      if current_user.has_voted_question_as_value?(question, params[:value])
        redirect_to params[:redirect_to], alert: "¡Ya has calificado esta pregunta!"
        return
      end

      if params[:value].to_i > 0
        current_user.update_attribute :likes, current_user.likes + 1
        current_user.update_attribute :dislike, current_user.likes - 1
      else
        current_user.update_attribute :likes, current_user.likes - 1
        current_user.update_attribute :dislike, current_user.likes + 1
      end

      vote = current_user.get_voted_question(question)
      vote.update_attribute :points, params[:value]
      redirect_to params[:redirect_to], notice: "¡Gracias por calificar la pregunta!"
      return
    end



    if params[:value].to_i > 0
      current_user.update_attribute :likes, current_user.likes + 1
      question.update_attribute :points, question.points + 1
      question.user_consult_question_votes.create user_id: current_user.id, points: 1
    else
      current_user.update_attribute :dislikes, current_user.likes + 1
      question.update_attribute :points, question.points - 1
      question.user_consult_question_votes.create user_id: current_user.id, points: -1
    end

    redirect_to params[:redirect_to], notice: "¡Gracias por calificar la pregunta!"
  end

  private

  def params_permit
    params.require(:question).permit(:text, consult_question_images_attributes: [:source, :id, :_destroy])
  end

  def load_data
    @subtitle = "Consultas"
  end

end

app/controllers/consults/weather_controller.rb
class Consults::WeatherController < ApplicationController

  before_action :load_data

  def index
    @country = Country.find_by_id @country_id
  end

  def load_data
    @subtitle = "Clima"
  end

end

app/views/consults/questions/_new_answer.html.erb
<% unless user_signed_in? %>
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#subscribe-modal">
  Responder
</button>
<% else %>
<% if direct == false %>
<%= link_to "Responder", consults_question_path(question, answer: true), class:"btn btn-primary btn-lg"%>
<% else %>
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#new-consult-answer">
  Responder
</button>
<!-- Modal -->
<div class="modal fade" id="new-consult-answer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <% @new_answer = question.answers.new
      if @new_answer.consult_answer_images.count == 0
        @new_answer.consult_answer_images.new
      end
      %>
      <%= nested_form_for @new_answer, as: :answer, url: consults_question_answers_path(question), method: :post do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Responder consulta en AgroNeto</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-sm-4">
            <label for="image">Adjunta una imagen o foto:</label>
            <% i = 0 %>
            <%= f.fields_for :consult_answer_images do |p_images_form| %>
            <div class="">
              <div style="margin-top: 20px;">
                <%= image_tag "no-image.png", class: "img-responsive preview-target" %>
              </div>
              <label class="btn btn-primary btn-file pull-right btn-block">
                <i class="fa fa-picture-o"></i>
                Seleccionar
                <%= p_images_form.file_field :source, value: nil, style: "display: none;", :"data-target" => "#preview-#{i}", class: "preview-file" %>
              </label>
              <br>


            </div>
            <% i += 1 %>
            <% end %>
          </div>
          <div class="col-sm-8">
            <label for="image">Respuesta:</label>
            <%= f.text_area :text, class: "form-control input-lg", placeholder: "Escribe aquí tu respuesta...", style: "height: 300px;" %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <input type="hidden" value="<%= request.path%>" name="redirect_to">
        <button type="submit" class="btn btn-primary">Guardar y Responder</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script>
$(function() {
  var fieldsCount,
  maxFieldsCount = 4,
  $addLink = $('a.add_nested_fields');

  function toggleAddLink() {
    $addLink.toggle(fieldsCount <= maxFieldsCount)
  }

  $(document).on('nested:fieldAdded', function() {
    fieldsCount += 1;
    toggleAddLink();
    $(".preview-file").change(function(){
  		readURL(this);
  	});
  });

  $(document).on('nested:fieldRemoved', function() {
    fieldsCount -= 1;
    toggleAddLink();
  });

  // count existing nested fields after page was loaded
  fieldsCount = $('form .fields').length;
  toggleAddLink();

  function readURL(input) {

		if (input.files && input.files[0]) {
			var reader = new FileReader();
			var element = $(input);

			reader.onload = function (e) {
				$(element.parent().parent().find(".preview-target")).attr('src', e.target.result);
			}

			reader.readAsDataURL(input.files[0]);
		}
	}

	$(".preview-file").change(function(){
		readURL(this);
	});

});
</script>
<% end %>
<% end %>

app/views/consults/questions/_sidebar.html.erb
<div class="visible-md visible-lg">
<%#= render "new", id: "1" %>
<% unless user_signed_in? %>
<div class="widget">
  <div class="post-entry-card" data-toggle="modal" data-target="#subscribe-modal">
    <%= image_tag "construction.jpg", class: "img-responsive" %>
    <div class="post-info">
      <h4 class="post-excerpt text-center">
        Subscríbete y haz parte de la red del Agro en Colombia, Latinoamérica y el Mundo
      </h4>
      <button type="button" class="btn btn-secondary btn-lg btn-block">
        Ingresar
      </button>
    </div>
  </div>
</div>
<% else %>
<div class="widget">
  <div class="post-entry-card" data-toggle="modal" data-target="#subscribe-modal">
    <%= image_tag "construction.jpg", class: "img-responsive" %>
    <div class="post-info">
      <h4 class="post-excerpt text-center">
        ¿Tienes una consulta, vendes o necesitas algo?
        <br>
        <b>¡En AgroNeto lo encuentras!</b>
      </h4>
      <%= link_to new_account_publication_path, class: "btn btn-secondary btn-lg btn-block"  do %>
      <i class="fa fa-star"></i>
      Publica tu anuncio
      <% end %>
    </div>
  </div>
</div>
<% end %>
</div>
<div class="visible-md visible-lg">
  <%= render "ads/02"%>
</div>
<div class="visible-md visible-lg" style="margin-top: 20px;">
  <%#= render "market/publications/relevant", size: "col-xs-6"  %>
</div>
<div class="">
  <%= render "landing/faces", users: User.profile_complete.order(created_at: :desc).first(16)  %>
</div>

app/views/consults/questions/index.html.erb
<%
meta title: "AgroNeto | Consultas",
description: @info.meta_description,
keywords: !@info.meta_keywords.nil? ? @info.meta_keywords.split(",") : []
%>

<% unless @info.meta_image.nil?

  meta og: {
    image: "#{@info.meta_image.url}"
  }

end %>

<%
meta twitter: {
  card: "AgroNeto | Consultas",
  site: "@AgroNetoOficial"
}
%>


<div class="row">
  <div class="col-md-8" style="margin-bottom: 20px;">
    <div class="">
    <%= render "new", id: 2 %>
    </div>
    <div class="btn-group text-center" style="margin-bottom: 20px;">
      <% if params[:scope].nil? || params[:scope] == "recents" %>
      <%= link_to "Recientes", consults_questions_path(scope: "recents"), class: "btn btn-primary" %>
      <%= link_to "Populares", consults_questions_path(scope: "hot"), class: "btn btn-default" %>
      <% else %>
      <%= link_to "Recientes", consults_questions_path(scope: "recents"), class: "btn btn-default" %>
      <%= link_to "Populares", consults_questions_path(scope: "hot"), class: "btn btn-primary" %>
      <% end %>
    </div>
    <% @questions.each_with_index do |question, index| %>
    <% if index == 1 %>
    <div class="visible-xs visible-sm">
      <%= render "ads/02"%>
    </div>
    <% end %>
    <% first_answer = question.answers.hot.first%>
    <div class="blog-container" style="margin-bottom: 40px;">

      <div class="blog-header">
        <!-- <div class="blog-cover"> -->
          <div class="blog-author--no-cover">
            <small>
              <fa class="fa fa-question-circle"></fa>
              Pregunta de:
            </small>
            <h3>
              <%= image_tag question.user.get_profile_image, class: "profile-icon"%>
              <%= question.user.name %>
            </h3>
          </div>
        <!-- </div> -->
      </div>

      <div class="blog-body">
        <div class="blog-title">
          <h3><%= link_to question.text, consults_question_path(question, back_to: request.original_fullpath) %></h3>
        </div>
        <div class="blog-summary">
          <% unless first_answer.nil? %>
          <p><i class="fa fa-comments"></i> Mejor Respuesta por: <%= first_answer.user.name %></p>
          <p><%= truncate first_answer.text, length: 200 %></p>
          <% else %>
          <p class="green"><i class="fa fa-comments"></i> <%= "Se el primero en responder" %></p>
          <% end %>
        </div>
        <div class="text-center">
          <%= render "new_answer", direct: false, question: question %>
          <br>
          <br>
        </div>
        <% unless question.consult_category.nil? %>
        <div class="blog-tags">
          <ul>
            <li><a href="#"><%= question.consult_category.name %></a></li>
          </ul>
        </div>
        <% end %>
      </div>

      <div class="blog-footer">
        <ul>
          <li class="published-date">Hace <%= distance_of_time_in_words(Time.now, question.created_at) %></li>
          <li style="padding-right: 10px;">
            <%#= social_share_button_tag("Consultas AgroNeto", :url => consults_question_path(question), desc: question.text, via: "AgroNetoOficial") %>
          </li>
          <li class="comments">
            <%= link_to voted_consults_question_path(question, value: 1, redirect_to: request.original_fullpath), class: "icon", method: :post do %>
              <i class="fa fa-thumbs-up fa-2x" style="color: #0F6A37;"></i>
              <span class="numero"><%= question.user_consult_question_votes.positives.count %></span>
            <% end %>
          </li>
          <li class="shares">
            <%= link_to voted_consults_question_path(question, value: -1, redirect_to: request.original_fullpath), class: "icon", method: :post do %>
              <i class="fa fa-thumbs-down fa-2x"></i>
              <span class="numero"><%= question.user_consult_question_votes.negatives.count %></span>
            <% end %>
          </li>
        </ul>
      </div>

    </div>

    <% end %>
    <%= paginate @questions %>
  </div>
  <div class="col-md-4">
    <%= render "sidebar" %>
  </div>
</div>

<% if params[:ask] == "true" %>
<script>
  $(function(){

    $(document).ready(function(){
      $("#new-consult-question-1").modal("show");
    });
  });
</script>
<% end %>

app/views/consults/questions/show.html.erb
<%
meta title: "AgroNeto | #{@question.text}",
description: @question.text,
keywords: !@info.meta_keywords.nil? ? @info.meta_keywords.split(",") : []
%>

<% unless @question.get_image.nil?

  meta og: {
    image: "#{@question.get_image}",
    url: consults_question_path(@question),
    title: "Consulta en AgroNeto",
    description: @question.text,
    type: "website"
  }

end %>

<%
meta twitter: {
  card: "AgroNeto | #{@question.text}",
  site: "@AgroNetoOficial"
}
%>


<% first_answer = @question.answers.hot.first%>
<div class="row">
  <div class="col-md-8">
    <div class="btn-group text-center" style="margin-bottom: 20px;">
      <% if params[:back_to].nil? %>
      <%= link_to "Volver a preguntas", consults_questions_path(scope: "hot"), class: "btn btn-primary" %>
      <% else %>
      <%= link_to "Volver a preguntas", params[:back_to], class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="blog-container">

      <div class="blog-header">
        <!-- <div class="blog-cover"> -->
        <div class="blog-author--no-cover">
          <small>
            <fa class="fa fa-question-circle"></fa>
            Pregunta de:
          </small>
          <% unless @question.user.nil? %>
          <h3><%= image_tag @question.user.get_profile_image, class: "profile-icon"%><%= @question.user.name %></h3>
          <% end %>
        </div>
        <!-- </div> -->
      </div>

      <div class="blog-body">
        <div class="blog-title">
          <h3><a href="#"><%= @question.text %></a></h3>
          <div class="text-center">
            <% if @question.consult_question_images.count > 0 %>
            <%= image_tag @question.consult_question_images.first.source.high.url, style: "width: 60%"%>
            <% end %>
          </div>
        </div>
        <% unless first_answer.nil? %>
        <div class="text-center">
          <%= render "new_answer", direct: true, question: @question %>
          <br><br>
        </div>
        <% end %>
        <% unless @question.consult_category.nil? %>
        <div class="blog-tags">
          <ul>
            <li><a href="#"><%= @question.consult_category.name %></a></li>
          </ul>
        </div>
        <% end %>
      </div>

      <div class="blog-footer">
        <ul>
          <li class="published-date">Hace <%= distance_of_time_in_words(Time.now, @question.created_at) %></li>
          <li style="padding-right: 10px;">
            <%#= social_share_button_tag("Consultas AgroNeto", :url => consults_question_path(@question), desc: @question.text, via: "AgroNetoOficial") %>
          </li>
          <li class="comments">
            <%= link_to voted_consults_question_path(@question, value: 1, redirect_to: request.original_fullpath), class: "icon", method: :post do %>
            <i class="fa fa-thumbs-up fa-2x" style="color: #0F6A37;"></i>
            <span class="numero"><%= @question.user_consult_question_votes.positives.count %></span>
            <% end %>
          </li>
          <li class="shares">
            <%= link_to voted_consults_question_path(@question, value: -1, redirect_to: request.original_fullpath), class: "icon", method: :post do %>
            <i class="fa fa-thumbs-down fa-2x"></i>
            <span class="numero"><%= @question.user_consult_question_votes.negatives.count %></span>
            <% end %>
          </li>
        </ul>
      </div>

    </div>
    <% unless first_answer.nil? %>
    <h3 class="text-center" style="margin-top: 40px;">Respuestas</h3>
    <% else %>
    <h3 class="text-center" style="margin-top: 40px;">Se el primero en responder</h3>
    <% end %>

    <div class="col-md-12 visible-xs visible-sm" id="relevant-publications" style="margin-top: 20px; margin-bottom: 20px;">
      <%= render "market/publications/relevant", size: "col-xs-6 col-sm-4 col-md-3" %>
    </div>


    <% @question.answers.hot.each do |answer| %>
    <%= render "answer", answer: answer %>
    <% end %>
    <div class="col-md-12 text-center" style="margin-top: 40px;">
      <%= render "new_answer", direct: true, question: @question %>
    </div>
  </div>
  <div class="col-md-4">
    <%= render "sidebar" %>
  </div>
</div>
<% if params[:answer] == "true" %>
<script>
  $(function(){

    $(document).ready(function(){
      $("#new-consult-answer").modal("show");
    });
  });
</script>
<% end %>