config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  default_url_options :host => "http://localhost:3000" if Rails.env == "development"
  default_url_options :host => "http://agroneto.com" if Rails.env == "production"

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  # mount Thredded::Engine => '/forum'

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "landing#index"

  resources :landing, only: [:index] do
    collection do
      get "select_country"
      post "accept_cookies"
      post "selected_country"
    end
  end
  resources :terms, only: [:index]
  resources :ads, as: "awesome", path: "awesome", only: [:show, :update]

  namespace :blog do
    resources :posts, only: [:index, :show]
  end

  namespace :consults do
    resources :questions, only: [:index, :show, :create, :update] do
      member do
        post "voted"
      end
      resources :answers, only: [:create, :update] do
        member do
          post "voted"
        end
      end
    end

    resources :weather, only: [:index]
  end

  namespace :market do
    resources :publications, only: [:index, :show] do
      collection do
        get "forum"
        get "autocomplete_subcategory_name"
        get "simple_new"
        post "simple_create"
      end
      member do
        post "ask"
        post "mark_as_favorite"
      end
      resources :purchases, only: [:create]
    end

    resources :feedbacks, only: [:new, :create]
  end

  namespace :account do
    resources :users, only: [:show, :edit, :update] do
      collection do
        get "dashboard"
        get "autocomplete_city_name"
        get "unsubscribe_emailing"
      end

      resources :contacts, only: [:index, :show, :create] do
        member do
          post "close"
        end
      end

      resources :notifications, only: [:show]
    end

    resources :feedbacks, only: [:index]
    resources :purchases, only: [:index, :show] do
      member do
        post "mark_as_charged"
        post "mark_as_sent"
        post "mark_as_payed"
      end
    end
    resources :reputations, only: [:index, :new, :update]

    resources :publications, only: [:index, :new, :create, :edit, :update] do
      collection do
        get "favorites" #COMO COMPRADOR
        get "purchases" #COMO COMPRADOR
        get "sales" #COMO VENDEDOR
      end
      member do
        post "make_gold"
        post "change_status"
        post "change_plan"
      end
    end

    resources :questions, only: [:index, :update]

    resources :achivements, only: [:index]
  end

  namespace :api do

    namespace :market do
      namespace :v1 do

        resources :subcategories, only: [:index]

        resources :commodities, only: [:index, :show]
        resources :publications, only: [:new, :create, :show]
      end
    end

    namespace :blog do
      namespace :v1 do
        resources :feed, only: [:index, :new, :create] do
          collection do
            post "upload_images"
          end
        end
        resources :categories, only: [:index]
        resources :posts, only: [:index, :show] do
          collection do
            get "hot"
          end
        end
      end
    end

    namespace :consults do
      namespace :v1 do
        resources :questions, only: [:index, :show, :create, :update] do
          member do
            post "voted"
            post "visited"
          end
          resources :answers, only: [:index, :create, :update] do
            member do
              post "voted"
            end
          end
        end
        resources :weather, only: [:index] do
          collection do
            post "historic"
            post "actual"
            post "forecast"
            post "maps"
          end
        end
      end
    end

    namespace :account do
      namespace :v1 do

        resources :cities, only: [:index]
        resources :feedbacks, only: [:create]
        resources :contacts, only: [:index, :show, :create]
        resources :countries, except: [:index]
        resources :interests, only: [:index]

        resources :sessions, except: [:index, :show, :create, :update, :new, :edit, :destroy] do
          collection do
            post "login"
            post "facebook_login"
            post "register"
          end
        end

        resources :ads, only: [:index] do
          member do
            post "read"
            get "engaged"
          end
        end

        resources :feedbacks, only: [:create]

        resources :notifications, only: [:index] do
          collection do
            get "unread_by_user"
            post "read_all"
          end
          member do
            post "arrived"
            post "read"
          end
        end

        resources :users, except: [:index, :new, :create, :edit, :destroy] do

          collection do
            get "terms"
          end

          member do
            post "confirm_email"
            post "upload_image"
            post "confirm_email"
          end
        end

      end
    end
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  before_action :load_data

  def index
    @all_posts = Post.actives

    @posts = @all_posts.where(country_id: @country_id)

    @all_publications = Publication.all
    @publications = @all_publications.ready.order(created_at: :desc).page(params[:page]).per(15)

    @features = @all_publications.ready.order(visits_count: :desc).first(16)
    if user_signed_in?
      @last_publications = current_user.visited_publications.ready.order(created_at: :desc).first(16)
    else
      @last_publications = @all_publications.ready.order(created_at: :desc).first(16)
    end

    @questions = ConsultQuestion.recents.first(5)

    @all_users = User.all
    @users = @all_users.profile_complete.order(created_at: :desc).page(params[:page]).per(15)

  end

  def select_country
    @not_show_main_banner = true
    @subtitle = "Seleccion de país"
    @countries = Country.all.order(name: :asc)
  end

  def selected_country
    country = Country.find params[:country_id]
    if user_signed_in?
      current_user.update_attribute :country_id, country.id
    else
      session[:country_id] = country.id
    end
    redirect_to params[:redirect_to], success: "Bienvenido a AgroNeto - #{country.name}"
  end

  def accept_cookies
    session[:cookies] = true
    render status: 200, json: {message: "Cookies aceptadas"}
  end

  private

  def load_data
    @subtitle = "El Mercado"
  end

end

app/views/landing/_faces.html.erb
<div class="row">
  <% users.each do |user| %>
  <div class="col-xs-3">
    <%= link_to account_user_path(user) do %>
      <%= image_tag user.get_profile_image, style: "width: 100%; border-radius: 100px; margin-bottom: 10px;" %>
    <% end %>
  </div>
  <% end %>
  <div class="col-md-12">
    + <%= User.count %> Usuarios
  </div>
</div>

app/views/landing/_new_landing.html.erb
<div class="row" style="margin-top: 40px;">
  <div class="col-xs-12 visible-xs">
    <h3 class="green">Consultas</h3>
  </div>
  <div class="col-xs-2 text-center">
    <h4 class="green">
      <i class="fa fa-question-circle fa-2x"></i> <br>
      <span class="hidden-xs">Consultas</span>
    </h4>
  </div>
  <div class="col-xs-10" style="border-left: 1px solid #f2f2f2;">
    <div class="row">
      <div class="col-md-12"></div>
      <% @questions.each do |question| %>
      <%= render "question_item", question: question %>
      <% end %>
    </div>
    <div class="text-right">
      <%= link_to "Ver más...", consults_questions_path(scope: "hot"), class: "btn btn-link" %>
    </div>
  </div>
</div>

<div class="row" style="margin-top: 40px;">
  <div class="col-xs-12 visible-xs">
    <h3 class="green">Noticias Destacadas</h3>
  </div>
  <div class="col-xs-2 text-center">
    <h4 class="green">
      <i class="fa fa-newspaper-o fa-2x"></i> <br>
      <span class="hidden-xs">Noticias Destacadas</span>
    </h4>
  </div>
  <div class="col-xs-10" style="border-left: 1px solid #f2f2f2;">
    <div class="grid blog-masonry">
      <div class="grid-sizer"></div>
      <% @posts.order("RANDOM()").first(2).each do |post| %>
      <%= render "post_item", post: post %>
      <% end %>
    </div>
    <div class="text-right">
      <%= link_to "Ver más...", blog_posts_path, class: "btn btn-link" %>
    </div>
  </div>
</div>

<div class="row" style="margin-top: 40px;">
  <div class="col-xs-12 visible-xs">
    <h3 class="green">Últimas Noticias</h3>
  </div>
  <div class="col-xs-2 text-center">
    <h4 class="green">
      <i class="fa fa-clock-o fa-2x"></i> <br>
      <span class="hidden-xs">Últimas Noticias</span>
    </h4>
  </div>
  <div class="col-xs-10" style="border-left: 1px solid #f2f2f2;">
    <div class="grid blog-masonry">
      <div class="grid-sizer"></div>
      <% @posts.order(date: :desc).first(2).each do |post| %>
      <%= render "post_item", post: post %>
      <% end %>
    </div>
    <div class="text-right">
      <%= link_to "Ver más...", blog_posts_path, class: "btn btn-link" %>
    </div>
  </div>
</div>

<% if @country_id == 1 || @country_id == 0 %>

<div class="row" style="margin-top: 40px;">
  <div class="col-xs-12 visible-xs">
    <h3 class="green">Publicaciones Destacadas</h3>
  </div>
  <div class="col-xs-2 text-center">
    <h4 class="green">
      <i class="fa fa-star-o fa-2x"></i> <br>
      <span class="hidden-xs">Publicaciones Destacadas</span>
    </h4>
  </div>
  <div class="col-xs-10" style="border-left: 1px solid #f2f2f2;">
    <%= render "market/publications/index/carusel_line", size: "col-md-3 col-sm-4 col-xs-6", publications: @features, id: "features" %>
  </div>
  <div class="text-right">
    <%= link_to "Ver más...", market_publications_path, class: "btn btn-link" %>
  </div>
  <div class="col-md-12">
    <hr>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 visible-xs">
    <h3 class="green">Últimas Publicaciones</h3>
  </div>
  <div class="col-xs-2 text-center">
    <h4 class="green">
      <i class="fa fa-clock-o fa-2x"></i> <br>
      <span class="hidden-xs">Últimas Publicaciones</span>
    </h4>
  </div>
  <div class="col-xs-10" style="border-left: 1px solid #f2f2f2;">
    <%= render "market/publications/index/carusel_line", size: "col-md-3 col-sm-4 col-xs-6", publications: @last_publications, id: "last_publications" %>
  </div>
  <div class="text-right">
    <%= link_to "Ver más...", market_publications_path, class: "btn btn-link" %>
  </div>
  <div class="col-md-12">
    <hr>
  </div>
</div>
<% end %>

app/views/landing/_old_landing.html.erb
<% if @empty == true %>
<div class="alert alert-info">
  No se encontraron resultados.
  <%= link_to landing_index_path, class: "btn btn-default" do %>
  <i class="fa fa-refresh"></i>
  Recargar...
  <% end %>
</div>
<% else %>
<div class="grid2 blog-masonry">
  <div class="grid-sizer2"></div>
  <% user_id = 48 unless @all_users.find_by_id(48).nil? %>
  <% user_id = @all_users.first.id if @all_users.find_by_id(48).nil? %>
  <%= render "ads/04" %>
  <%# @all_publications.where(user_id: user_id).order("RANDOM()").limit(6).each do |publication| %>
    <%#= render "landing/publication_item", publication: publication %>
  <%# end %>
  <% (0..49).each do |j| %>
    <% if j < @publications.count %>
      <%= render "landing/publication_item", publication: @publications[j] %>
    <% end %>
    <% if j < @users.count %>
      <%= render "landing/user_item", user: @users[j] %>
    <% end %>
  <% end %>
</div>
<% end %>
<%= paginate @users %>

app/views/landing/_post_item.html.erb
<div class="grid-item">
  <div class="post-entry-card">
    <% if post.subcategories.count > 0 %>
    <div class="post-header" style="<%= post.subcategories.first.category.color %>">
      <%= post.subcategories.first.category.name %>
    </div>
    <% end %>
    <%= link_to blog_post_path(post), style: "position: relative;" do %>
    <%= image_tag post.image.mid.url, class: "img-responsive", alt: "Imagen" %>
    <% end %>
    <div class="post-info">
      <h3 class="post-title">
        <%= link_to blog_post_path(post) do %>
        <%= post.title %>
        <% end %>
      </h3>
      <p class="post-excerpt">
        <%= post.abstract %>
      </p>
      <span class="post-meta">
        <i class="fa fa-map-marker"></i> <%= post.get_scope %> / <%= post.date.strftime("%d de %b") %>
      </span>
      <%= link_to "Leer más", blog_post_path(post), class: "read-more pull-right" %>
    </div>
  </div>
</div>

app/views/landing/_publication_item.html.erb
<div class="grid-item2">
  <div class="post-entry-card">
    <%= link_to market_publication_path(publication) do %>
      <%= image_tag publication.get_image("mid_original"), class: "img-responsive" %>
      <hr style="margin-bottom: -5px; ">
      <div class="post-info">
        <p class="green" style="font-size: 25px; font-weight: bold;">
          <% if publication.in_need == true %>
          <span class="label label-secondary pull-right">
            Se busca
          </span>
          <% end %>
          <% if publication.user.is_official == true %>
          <span class="label label-primary secondary-color-font pull-right">
            <i class="fa fa-star"></i> Tienda oficial
          </span>
          <% end %>
          <% unless publication.in_need == true %>
          <%= number_to_currency publication.price, precision: 0, delimiter: "." %>
          <% end %>
        </p>
        <p style="color: #777; font-size: 24px; margin-bottom: 20px;">
          <%= publication.title %>
        </p>
        <span class="label label-primary">
          <%= publication.subject %>
        </span>
        <span class="label label-secondary">
          <%= publication.subcategory.category.name %> <i class="fa fa-chevron-right"></i> <%= publication.subcategory.name %>
        </span>
        <span class="label label-default">
          <%= publication.get_kind %>
        </span>
        <% if publication.subject == Publication::INMUEBLES %>
        <span class="label label-secondary">
          <%= publication.get_mode %>
        </span>
        <% end %>
        <br>
        <span class="post-meta">
          <i class="fa fa-map-marker"></i> <%= publication.city.name.downcase.camelcase %> - <%= publication.city.department.name.downcase.camelcase %>
          <br>
          <% if publication.in_need == true %>
          <%= publication.purchases.count %> vendidos 
          /
          <% end %>
          <%= publication.visits_count %> vistas
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/landing/_question_item.html.erb
<% first_answer = question.answers.hot.first%>
<div class="row">
  <div class="col-xs-3 text-center hidden-xs">
    <%= link_to account_user_path(question.user) do %>
    <%= image_tag question.user.get_profile_image, style: "width: 60%; border-radius: 100px;" %>
    <br>
    Pregunta por: <br>
    <span class="green">
      <%= question.user.name%>
    </span>
    <% end %>
  </div>
  <div class="col-xs-12 visible-xs">
    <%= link_to account_user_path(question.user) do %>
      Pregunta por: <%= question.user.try(:name)%>
    <% end %>
  </div>
  <div class="col-xs-9">
    <h4 class="hidden-xs">
      <%= link_to consults_question_path(question), style: "color: #777;" do %>
      <%= question.text %>
      <% end %>
    </h4>
    <p class="visible-xs" style="font-weight: bold;">
      <%= link_to consults_question_path(question), style: "color: #777;" do %>
      <%= question.text %>
      <% end %>
    </p>
    <p>
      <% unless first_answer.nil? %>
      <p><i class="fa fa-comments"></i> Mejor Respuesta por: <%= first_answer.user.try(:name) %></p>
      <p><%= truncate first_answer.text, length: 200 %></p>
      <% else %>
      <p class="green"><i class="fa fa-comments"></i> <%= "Se el primero en responder" %></p>
      <% end %>
    </p>
    <p class="text-left">
      <%= render "consults/questions/new_answer", direct: false, question: question %>
      <br>
      <br>
    </p>
    <% unless question.consult_category.nil? %>
    <p>
      <span class="label label-primary">
        <%= question.consult_category.name %>
      </span>
    </p>
    <% end %>
  </div>
  <div class="col-xs-12">
    <hr>
  </div>
</div>

app/views/landing/_sidebar.html.erb
<div class="sidebar visible-lg visible-md">
  <div class="widget visible-md visible-lg">
    <%= render "ads/02"%>
  </div>
  <!-- widget -->
  <div class="widget">
    <h1 class="text-center label label-primary" style="font-size: 20px;">
      <%= number_with_delimiter (@all_publications.all.sum(:visits_count) + @all_posts.sum(:views_count)), delimiter: "." %>
      Visitas
    </h1>
  </div>
  <div class="widget">
    <h1 class="text-center label label-secondary" style="font-size: 20px;">
      <%= number_with_delimiter @all_publications.count + @all_posts.count, delimiter: "." %>
      Publicaciones
    </h1>
  </div>
  <div class="widget">
    <h1 class="text-center label label-primary" style="font-size: 20px;">
      <%= number_with_delimiter @all_users.count, delimiter: "." %>
      Usuarios
    </h1>
  </div>
  <div class="widget">
    <%= render "landing/faces", users: User.profile_complete.order(created_at: :desc).first(8)  %>
  </div>
</div>
<div class="widget visible-lg visible-md">
  <h4 class="widget-title">Últimas noticias</h4>
  <% @posts.order(date: :desc).offset(2).first(5).each do |post| %>
  <%= link_to blog_post_path post do %>
  <div class="media">
    <div class="media-left">
        <%= image_tag post.image.low.url, class: "media-object", style: "width: 64px;" %>
    </div>
    <div class="media-body">
      <h4 class="media-heading">
        <%= post.title%>
      </h4>
      <p class="text-right">
        <%= post.date.strftime("%d de %b, %Y")%>
      </p>
    </div>
  </div>
  <% end %>
  <hr>
  <% end %>
  <%= link_to "Ver más...", blog_posts_path, class: "btn btn-link"%>
</div>
<div class="widget visible-md visible-lg">
  <%= render "ads/03"%>
</div>
<!-- <div class="widget">
  <div class="post-entry-card">
    <%= image_tag "market.png", class: "img-responsive" %>
    <div class="post-info">
      <h4 class="post-excerpt text-center">
        Conoce El Mercado dedicado a los productos del Agro.
      </h4>
      <%= render "layouts/searchbar", classs: "" %>
    </div>
  </div>
</div> -->
<!-- <div class="widget">
  <div class="post-entry-card">
    <%= image_tag "news.png", class: "img-responsive" %>
    <div class="post-info">
      <h4 class="post-excerpt text-center">
        Informate con las últimas noticias en el mundo del Agro.
      </h4>
      <%= link_to "Noticias", blog_posts_path, class: "btn btn-secondary btn-block btn-lg"%>
    </div>
  </div>
</div> -->
<!-- <div class="widget">
  <div class="post-entry-card" data-toggle="modal" data-target="#subscribe-modal">
    <%= image_tag "forum.png", class: "img-responsive" %>
    <div class="post-info">
      <h4 class="post-excerpt text-center">
        Conoce nuestra sección de AgroConsultas, has preguntas y recibe respuestas realcionadas con el Agro.
      </h4>
      <%= link_to "AgroConsultas", "/consults/questions?scope=hot", class: "btn btn-secondary btn-block btn-lg"%>
    </div>
  </div>
</div> -->
<!-- <div class="twitter" id="twitter-timeline-container" style="max-height: 600px; overflow-y: auto;">
</div> -->

app/views/landing/_user_item.html.erb
<div class="grid-item2">
  <div class="post-entry-card">
    <%= link_to account_user_path(user) do %>
    <div class="text-center">
      <%= image_tag user.get_profile_image, style: "width: 60%;" %>
      <!-- border-radius: 200px; -->
    </div>

    <hr style="margin-bottom: -5px; ">
    <div class="post-info">
      <% if user.is_official == true %>
      <span class="label label-primary secondary-color-font pull-right" style="font-size: 18px;">
        <i class="fa fa-star"></i> Tienda oficial
      </span>
      <% end %>
      <p class="green" style="font-size: 20px; font-weight: bold;">
        <%= user.name %>
      </p>
      <p style="color: #777; height: 60px;">
        <%= truncate user.main_activity, length: 150, omission: "(Click para ver más...)" %>
      </p>
      <span class="label label-primary">
        <%= user.profession %>
      </span>
      <br>
      <% unless user.city.nil? %>
      <span class="post-meta">
        <i class="fa fa-map-marker"></i> <%= user.city.name.downcase.camelcase %> - <%= user.city.department.name.downcase.camelcase %>
      </span>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/landing/index.html.erb
<%
meta title: "AgroNeto | #{@info.blog_tab_title}",
description: @info.meta_description,
keywords: !@info.meta_keywords.nil? ? @info.meta_keywords.split(",") : []
%>

<% unless @info.meta_image.nil?

meta og: {
  image: "#{@info.meta_image.url}"
}

end %>

<%
meta twitter: {
  card: "AgroNeto | #{@info.blog_tab_title}",
  site: "@AgroNetoOficial"
}
%>

<div class="row">
  <!-- MAIN CONTENT -->
  <!-- <div class="col-md-12">
  <h3 class="widget-title">EL MERCADO</h3>
</div> -->
<!-- <div class="col-md-12 visible-xs visible-sm">
<%#= render "ads/02"%>
</div> -->
<!-- <div class="col-md-12 visible-xs visible-sm">
  <%#= render "consults/questions/new", id: "2" %>
</div> -->
<div class="col-md-3 visible-lg visible-md" style="position: fixed; left: 3%;">
  <!-- end widget -->
  <% unless user_signed_in? %>
  <div class="widget">
    <div class="post-entry-card" data-toggle="modal" data-target="#subscribe-modal">
      <%= image_tag "construction.jpg", class: "img-responsive" %>
      <div class="post-info">
        <h4 class="post-excerpt text-center">
          Subscríbete y haz parte de la red del Agro en Colombia, Latinoamérica y el Mundo
        </h4>
        <button type="button" class="btn btn-secondary btn-lg btn-block">
          Ingresar
        </button>
      </div>
    </div>
  </div>
  <% else %>
  <div class="widget">
    <div class="post-entry-card" data-toggle="modal" data-target="#subscribe-modal">
      <%= image_tag "construction.jpg", class: "img-responsive" %>
      <div class="post-info">
        <h4 class="post-excerpt text-center">
          ¿Tienes una consulta, vendes o necesitas algo?
          <br>
          <b>¡En AgroNeto lo encuentras!</b>
        </h4>
        <button type="button" class="btn btn-secondary btn-lg btn-block" data-toggle="modal" data-target="#new-feed-modal">
          Publica tu anuncio
        </button>
      </div>
    </div>
  </div>
  <% end %>
  <div class="btn-group-vertical visible-md visible-lg">
    <button type="button" class="btn" ng-class="{'btn-primary': scope == 'all' || scope == '', 'btn-default': scope != 'all' || scope != ''}" ng-click="GetFeed('')">
      Todos
    </button>
    <button type="button" class="btn" ng-class="{'btn-primary': scope == 'consults', 'btn-default': scope != 'consults'}" ng-click="GetFeed('consults')">
      Consultas
    </button>
    <button type="button" class="btn" ng-class="{'btn-primary': scope == 'market', 'btn-default': scope != 'market'}" ng-click="GetFeed('market')">
      Mercado
    </button>
    <button type="button" class="btn" ng-class="{'btn-primary': scope == 'posts', 'btn-default': scope != 'posts'}" ng-click="GetFeed('posts')">
      Noticias
    </button>
  </div>
</div>
<div class="col-md-6 col-md-offset-3">
  <!-- latest posts -->
  <div class="no-padding-top">
    <%#= render "consults/questions/new", id: "2" %>
  </div>
  <div class="no-padding-top">
    <%= render "api/blog/v1/feed/list" %>
  </div>
  <!-- end latest posts -->
</div>
<!-- <div class="col-md-12 visible-xs visible-sm">
<%#= render "ads/03"%>
</div> -->
<!-- END MAIN CONTENT -->
<!-- SIDEBAR CONTENT -->
<div class="col-md-3 col-lg-3">
  <%= render "sidebar" %>
</div>
<!-- <div class="col-md-9" style="margin-bottom: 20px;">
  <%#= render "layouts/searchbar", classs: "" %>
</div> -->

<!-- END SIDEBAR CONTENT -->
</div>

app/views/landing/select_country.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title text-center">En que país te encuentras</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <%= image_tag @info.logo.url, style: "width: 100%;" %>
          </div>
          <% @countries.order(id: :asc).each do |country| %>
            <%= link_to main_app.selected_country_landing_index_path(redirect_to: params[:redirect_to], country_id: country.id), method: :post do %>
              <div class="col-xs-3 text-center" style="margin-top: 40px;">
                <%= image_tag country.flag.square.url, alt: country.name, style: "width: 100%; border-radius: 100px;" %>
                <br>
                <b><%= country.name %></b>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>