config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  default_url_options :host => "http://localhost:3000" if Rails.env == "development"
  default_url_options :host => "http://agroneto.com" if Rails.env == "production"

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  # mount Thredded::Engine => '/forum'

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "landing#index"

  resources :landing, only: [:index] do
    collection do
      get "select_country"
      post "accept_cookies"
      post "selected_country"
    end
  end
  resources :terms, only: [:index]
  resources :ads, as: "awesome", path: "awesome", only: [:show, :update]

  namespace :blog do
    resources :posts, only: [:index, :show]
  end

  namespace :consults do
    resources :questions, only: [:index, :show, :create, :update] do
      member do
        post "voted"
      end
      resources :answers, only: [:create, :update] do
        member do
          post "voted"
        end
      end
    end

    resources :weather, only: [:index]
  end

  namespace :market do
    resources :publications, only: [:index, :show] do
      collection do
        get "forum"
        get "autocomplete_subcategory_name"
        get "simple_new"
        post "simple_create"
      end
      member do
        post "ask"
        post "mark_as_favorite"
      end
      resources :purchases, only: [:create]
    end

    resources :feedbacks, only: [:new, :create]
  end

  namespace :account do
    resources :users, only: [:show, :edit, :update] do
      collection do
        get "dashboard"
        get "autocomplete_city_name"
        get "unsubscribe_emailing"
      end

      resources :contacts, only: [:index, :show, :create] do
        member do
          post "close"
        end
      end

      resources :notifications, only: [:show]
    end

    resources :feedbacks, only: [:index]
    resources :purchases, only: [:index, :show] do
      member do
        post "mark_as_charged"
        post "mark_as_sent"
        post "mark_as_payed"
      end
    end
    resources :reputations, only: [:index, :new, :update]

    resources :publications, only: [:index, :new, :create, :edit, :update] do
      collection do
        get "favorites" #COMO COMPRADOR
        get "purchases" #COMO COMPRADOR
        get "sales" #COMO VENDEDOR
      end
      member do
        post "make_gold"
        post "change_status"
        post "change_plan"
      end
    end

    resources :questions, only: [:index, :update]

    resources :achivements, only: [:index]
  end

  namespace :api do

    namespace :market do
      namespace :v1 do

        resources :subcategories, only: [:index]

        resources :commodities, only: [:index, :show]
        resources :publications, only: [:new, :create, :show]
      end
    end

    namespace :blog do
      namespace :v1 do
        resources :feed, only: [:index, :new, :create] do
          collection do
            post "upload_images"
          end
        end
        resources :categories, only: [:index]
        resources :posts, only: [:index, :show] do
          collection do
            get "hot"
          end
        end
      end
    end

    namespace :consults do
      namespace :v1 do
        resources :questions, only: [:index, :show, :create, :update] do
          member do
            post "voted"
            post "visited"
          end
          resources :answers, only: [:index, :create, :update] do
            member do
              post "voted"
            end
          end
        end
        resources :weather, only: [:index] do
          collection do
            post "historic"
            post "actual"
            post "forecast"
            post "maps"
          end
        end
      end
    end

    namespace :account do
      namespace :v1 do

        resources :cities, only: [:index]
        resources :feedbacks, only: [:create]
        resources :contacts, only: [:index, :show, :create]
        resources :countries, except: [:index]
        resources :interests, only: [:index]

        resources :sessions, except: [:index, :show, :create, :update, :new, :edit, :destroy] do
          collection do
            post "login"
            post "facebook_login"
            post "register"
          end
        end

        resources :ads, only: [:index] do
          member do
            post "read"
            get "engaged"
          end
        end

        resources :feedbacks, only: [:create]

        resources :notifications, only: [:index] do
          collection do
            get "unread_by_user"
            post "read_all"
          end
          member do
            post "arrived"
            post "read"
          end
        end

        resources :users, except: [:index, :new, :create, :edit, :destroy] do

          collection do
            get "terms"
          end

          member do
            post "confirm_email"
            post "upload_image"
            post "confirm_email"
          end
        end

      end
    end
  end

end

app/controllers/account/publications_controller.rb
class Account::PublicationsController < ApplicationController

  before_action :authenticate_user!, if: lambda { |controller| session[:native_app].nil? }
  acts_as_token_authentication_handler_for User, unless: lambda { |controller| session[:native_app].nil? }

  before_action :load_data


  def index
    @all_publications = current_user.publications.order(created_at: :desc)
    if params[:scope] == "paused"
      @publications = @all_publications.paused
    elsif params[:scope] == "finished"
      @publications = @all_publications.finished
    else
      @publications = @all_publications.actives
    end
  end

  def favorites
    @favorites = current_user.favorites_publications.actives
  end

  def purchases
  end

  def sales
  end

  def new

    if current_user.get_profile_percent < 100
      redirect_to edit_account_user_path(current_user), alert: "¡Para publicar debes completar tu perfil!"
      return
    end

    check_step

    @publication = current_user.publications.new

    if @step == 1

      unless params[:in_need].nil?
        @in_need = true if params[:in_need] == "true"
        @in_need = false if params[:in_need] != "true"
      end

      if !params[:subject].nil?
        @selected_subject = params[:subject]
        @categories = Category.includes(:subcategories).by_subject(params[:subject]).order(name: :asc)
        unless params[:category_id].nil?
          @selected_category = @categories.find_by_id params[:category_id]
          unless @selected_category.nil?
            @subcategories = @selected_category.subcategories.order(name: :asc)
            unless params[:subcategory_id].nil?
              @selected_subcategory = @subcategories.find_by_id params[:subcategory_id]
            else
              if @selected_category.subcategories.count == 1
                @selected_subcategory = @subcategories.first
              end
            end
          end
        end
      elsif !params[:sample_id].nil?
        sample = Publication.find params[:sample_id]
        @selected_subject = sample.subject
        @categories = Category.includes(:subcategories).by_subject(@selected_subject)
        @selected_category = @categories.find_by_id sample.subcategory.category.id
        @subcategories = @selected_category.subcategories
        @selected_subcategory = @subcategories.find_by_id sample.subcategory.id
      end
    end

  end

  def create

    check_step
    @plans = Plan.all.order(priority: :asc)
    @publication = current_user.publications.new params_permit_create
    params[:publication][:step] = @step

    if @publication.save
      @publication.update_attribute :plan_id, @plans.first.id
      redirect_to edit_account_publication_path(@publication, step: 2)
    else
      redirect_to new_account_publication_path(step: 1), alert: "¡Ha ocurrido un error inesperado!"
    end
  end

  def edit
    @step = params[:step].to_i
    @plans = Plan.all.order(priority: :asc)

    @publication = current_user.publications.find params[:id]

    validate_steps

    @publication.publication_images.where(source: nil).delete_all

    if @publication.publication_images.count == 0
      @publication.publication_images.new
    end

    unless @publication.in_need.nil?
      @in_need = @publication.in_need
    end

    unless params[:in_need].nil?
      @in_need = true if params[:in_need] == "true"
      @in_need = false if params[:in_need] != "true"
    end

    unless params[:errors].nil?
      @errors = JSON.parse params[:errors]
    end

    if @step == 2 && @publication.subject == Publication::ANIMALES && !@publication.age.nil?
      @age_selector = @publication.age.to_s.split(" ")
      if @age_selector.count > 0
        @age_selector = @age_selector[1]
      end
      @publication.age = @publication.age.to_s.gsub(" ", "").gsub("Año(s)", "").gsub("Mes(es)", "")
    end

    if !@publication.status.nil? && @publication.status > 0
      @selected_subject = @publication.subject
      @categories = Category.includes(:subcategories).by_subject(@publication.subject).order(name: :asc)
      @selected_category = @categories.find_by_id @publication.subcategory.category_id
      @subcategories = @selected_category.subcategories.order(name: :asc)
      @selected_subcategory = @subcategories.find_by_id @publication.subcategory_id

      if !params[:subject].nil?
        @selected_subject = params[:subject]
        @categories = Category.includes(:subcategories).by_subject(params[:subject]).order(name: :asc)
        unless params[:category_id].nil?
          @selected_category = @categories.find_by_id params[:category_id]
          unless @selected_category.nil?
            @subcategories = @selected_category.subcategories.order(name: :asc)
            unless params[:subcategory_id].nil?
              @selected_subcategory = @subcategories.find_by_id params[:subcategory_id]
            else
              if @selected_category.subcategories.count == 1
                @selected_subcategory = @subcategories.first
              end
            end
          end
        end
      end

      #@plans = @plans.where("priority > ?", @publication.plan.priority)
    end

    check_step
  end

  def update

    check_step

    @publication = current_user.publications.find params[:id]
    params[:publication][:step] = @step

    #Capitalización de campos de texto para uniformidad
    params[:publication][:title] = params[:publication][:title].titleize unless params[:publication][:title].nil?
    # params[:publication][:description] = params[:publication][:description].capitalize unless params[:publication][:description].nil?
    params[:publication][:warranty_description] = params[:publication][:warranty_description].capitalize unless params[:publication][:warranty_description].nil?

    if @publication.update params_permit_update
      @publication.update_attribute(:age, "#{params[:publication][:age]} #{params_permit_create_none[:age_selector]}") if @step == 2 && @publication.subject == Publication::ANIMALES

      if @step == 2
        if @publication.publication_images.where.not(source: nil).count == 0
          redirect_to edit_account_publication_path(@publication, step: @step), alert: "Debes ingresar al menos 1 imagen."
          return
        end
      end

      @publication.update_attribute(:end_date, Time.now + 1.month) if @step == 3 && @publication.end_date.nil?

      if @step +1 < 4
        redirect_to edit_account_publication_path(@publication, step: @step + 1)
      else
        if @publication.status == 0 || @publication.status.nil?
          Notification.create_and_send(Notification::PUBLICATION_CREATED, @publication, current_user)
        end
        @publication.update_attribute(:status, 1) if @step == 3
        redirect_to edit_account_publication_path(@publication, step: @step + 1), notice: "Tu publicación ya se encuentra al aire. Usa tus puntos para más exposición y tiempo ilimitado para tu publicación."
      end
    else

      @publication.title = params[:publication][:title].titleize unless params[:publication][:title].nil?
      # @publication.description = params[:publication][:description].capitalize unless params[:publication][:description].nil?
      @publication.kind = params[:publication][:kind] unless params[:publication][:kind].nil?
      @publication.units = params[:publication][:units] unless params[:publication][:units].nil?
      @publication.price = params[:publication][:price] unless params[:publication][:price].nil?
      @publication.city_id = params[:publication][:city_id] unless params[:publication][:city_id].nil?
      @publication.address = params[:publication][:address] unless params[:publication][:address].nil?
      @publication.year = params[:publication][:year] unless params[:publication][:year].nil?
      @publication.year = params[:publication][:year] unless params[:publication][:year].nil?
      @publication.brand = params[:publication][:brand] unless params[:publication][:brand].nil?
      @publication.km = params[:publication][:km] unless params[:publication][:km].nil?
      @publication.model = params[:publication][:model] unless params[:publication][:model].nil?
      @publication.transmission = params[:publication][:transmission] unless params[:publication][:transmission].nil?
      @publication.cylinder = params[:publication][:cylinder] unless params[:publication][:cylinder].nil?
      @publication.color = params[:publication][:color] unless params[:publication][:color].nil?
      @publication.fuel_type = params[:publication][:fuel_type] unless params[:publication][:fuel_type].nil?
      @publication.shipping = params[:publication][:shipping] unless params[:publication][:shipping].nil?
      @publication.pickup = params[:publication][:pickup] unless params[:publication][:pickup].nil?
      @publication.shipping_price = params[:publication][:shipping_price] unless params[:publication][:shipping_price].nil?
      if @step == 2 && @publication.subject == Publication::ANIMALES
        @publication.age = "#{params[:publication][:age]} #{params_permit_create_none[:age_selector]}" unless params[:publication][:age].nil?
      end
      @publication.willing_to_move = params[:publication][:willing_to_move] unless params[:publication][:willing_to_move].nil?
      @publication.to_agree = params[:publication][:to_agree] unless params[:publication][:to_agree].nil?
      @publication.with_ac = params[:publication][:with_ac] unless params[:publication][:with_ac].nil?
      @publication.uniq_owner = params[:publication][:uniq_owner] unless params[:publication][:uniq_owner].nil?
      @publication.for_adoption = params[:publication][:for_adoption] unless params[:publication][:for_adoption].nil?
      @publication.for_adoption = params[:publication][:number] unless params[:publication][:number].nil?
      @publication.for_adoption = params[:publication][:total_mtr] unless params[:publication][:total_mtr].nil?

app/controllers/api/market/v1/commodities_controller.rb
class Api::Market::V1::CommoditiesController < Api::ApiNsController
  def index
    @full_data = false
    @commodities = Commodity.all.order(priority: :asc)
  end

  def show
    @full_data = true
    @commodities = Commodity.find params[:id]

    if params[:scope] == "anual"
      @variations = @commodities.variations.where(created_at: Date.today.at_beginning_of_year..Date.today)
    else
      @variations = @commodities.variations.where(created_at: (Date.today - 1.month)..Date.today)
    end

    render "index"
  end
end

app/controllers/api/market/v1/publications_controller.rb
class Api::Market::V1::PublicationsController < Api::ApiNsController

  layout "layouts/application_api"

  def show
    @publication = Publication.ready.find params[:id]
    @user = @publication.user
    @reputation = @publication.user.get_reputation_data
    @publication.update_attribute :visits_count, @publication.visits_count + 1
  end

end

app/controllers/api/market/v1/subcategories_controller.rb
class Api::Market::V1::SubcategoriesController < Api::ApiNsController

  def index
    @aux = Subcategory.includes(:category).actives.where({categories: {for_news: [false, nil]}}).search(params[:term]).references(:category)
    @subcategories = []
    @aux.each do |sub|
      tmp = @subcategories.find {|s| s.name.downcase == sub.name.downcase }
      if tmp.nil?
        @subcategories.push sub
      end
    end
  end

end

app/controllers/market/feedbacks_controller.rb
class Market::FeedbacksController < ApplicationController

  before_action :authenticate_user!
  before_action :load_data

  def new
    @feedback = current_user.feedbacks.new
    @publication_id = params[:publication_id]
  end

  def create
    @feedback = current_user.feedbacks.new params_permit_create
    if @feedback.save
      if params[:redirect_to].nil?
        redirect_to market_publication_path(@feedback.publication), notice: "¡Gracias por contactarnos! el caso será estudiado y te notificaremos con la respuesta"
      else
        redirect_to params[:redirect_to], notice: "¡Gracias por contactarnos! el caso será estudiado y te notificaremos con la respuesta"
      end
    else
      if params[:redirect_to].nil?
        @publication_id = params[:feedback][:publication_id]
        render :new
      else
        redirect_to params[:redirect_to], notice: @feedback.errors.full_message.to_sentence
      end
    end
  end

  private

  def load_data
    @subtitle = "Solución de problemas"
  end

  def params_permit_create
    params.require(:feedback).permit(:subject, :details, :publication_id)
  end

end

app/views/market/publications/_relevant.html.erb
<%
aggs = {kind: {min_doc_count: 1}, subject: {min_doc_count: 1}, subcategory_name: {min_doc_count: 1}, category_name: {min_doc_count: 1}, city_name: {min_doc_count: 1}}
relevant_publications = Publication.ready.search "*",
operator: "or",
fields: [:subcategory_name, :category_name, :title],
aggs: aggs,
smart_aggs: false,
where: {status: 1},
misspellings: {below: 5},
track: user_signed_in? ? {user_id: current_user.id} : false,
suggest: true,
boost_by: {visits_count: {factor: 50}},
boost_where: {plan_id: [{value: 1, factor: 10}, {value: 2, factor: 100}]},
page: 1, per_page: 20


%>
<div class="row">
  <div class="col-md-12">
    <%= render "market/publications/index/carusel_line", size: size, publications: relevant_publications, id: "history" %>
  </div>
</div>

app/views/market/publications/forum.html.erb
<%= render "layouts/section_in_construction", message: "Muy pronto tendremos una sección de consultas dedicado a los temas del Agro", content: "Si deseas recibir información acerca de nosotros y nuestras actualizaciones te invitamos a registrate, sin costo, prometemos solo contactarte cuando sea algo importante."%>

app/views/market/publications/index.html.erb
<% if !params[:search_term].nil? && params[:search_term] != "" %>
  <div class="row">
    <div class="col-md-3 hidden-xs hidden-sm">
      <%= render "market/publications/index/sidebar" %>
    </div>
    <div class="col-md-9" style="border-left: 1px solid #f2f2f2;">
      <div class="grid2 blog-masonry">
        <div class="grid-sizer2"></div>

        <% if @publications.count == 0%>
        <%= render "layouts/no_results", namespace: "Publicaciones" %>
        <% end %>
        <% if params[:view] == "list" %>
          <% @publications.each do |publication| %>
            <%= render "market/publications/index/list_item", publication: publication %>
          <% end %>
        <% else %>
          <div class="row">
            <% @publications.each do |publication| %>
              <%= render "market/publications/index/grid_item", publication: publication %>
            <% end %>
          </div>
        <% end %>

      </div>
      <%= paginate @publications %>
    </div>
  </div>
  <%= render "market/publications/index/filters_modal" %>
<% else %>
  <% if session[:native_app].nil? %>
    <%= render "market/publications/index/no_search" %>
  <% else %>
  <%= render "market/publications/index/search" %>
  <% end %>
<% end %>



<%#= render "layouts/section_in_construction", message: "Muy pronto tendremos un Mercado dedicado a los productos y servicios del Agro", content: "Si deseas recibir información acerca de nosotros y nuestras actualizaciones te invitamos a registrate, sin costo, prometemos solo contactarte cuando sea algo importante."%>

app/views/market/publications/show.html.erb
<%
meta title: "AgroNeto | #{@publication.title}",
description: "AgroNeto el mercado del Agro.",
keywords: "AgroNeto,Agro,Productos,Mercado,#{@publication.subcategory.name},#{@publication.subcategory.category.name},#{@publication.subject}".split(",")
%>

<%

meta og: {
  image: "#{@publication.get_image('high')}",
  url: market_publication_url(@publication),
  title: @publication.title,
  description: @publication.get_kind,
  type: "website"
}
%>
<%
meta twitter: {
  card: "AgroNeto | #{@publication.title}",
  site: "@AgroNetoOficial"
}
%>

<div class="row">
  <div class="col-md-12 text-right">
    <%= link_to "Denunciar", new_market_feedback_path(publication_id: @publication.id) %> |
    <%= link_to "Publicar uno igual", new_account_publication_path(sample_id: @publication.id) %>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2 text-center">
    <h2 class="green">
      <%= @publication.title %>
      <br>
      <small>

        <span class="label label-primary">
          <%= @publication.subject %>
        </span>
        <span class="label label-secondary">
          <%= @publication.subcategory.category.name %> <i class="fa fa-chevron-right"></i> <%= @publication.subcategory.name %>
        </span>
        <span class="label label-default">
          <%= @publication.get_kind %>
        </span>
        <% if @publication.subject == Publication::INMUEBLES %>
        <span class="label label-secondary">
          <%= @publication.get_mode %>
        </span>
        <% end %>
        <% unless @publication.city.nil? %>
          <br>
          <%= image_tag @publication.city.department.country.flag.url, style: "width: 30px; border-radius: 30px;" %>
        <% end %>
      </small>
    </h2>
    <hr>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <%= render "market/publications/show/images"%>
  </div>
  <div class="col-md-6">
    <% if @publication.in_need == true %>
    <h1 style="margin-top: -5px; margin-bottom: 20px;">
      <span class="label label-secondary">
        Se busca
      </span>
    </h1>
    <% end %>
    <% if @publication.user.is_official == true %>
    <span class="label label-primary secondary-color-font pull-right" style="font-size: 25px;">
      <i class="fa fa-star"></i> Tienda oficial
    </span>
    <% end %>
    <% unless @publication.in_need == true %>
    <p class="green" style="font-size: 40px;">
      <%= number_to_currency @publication.price, precision: @publication.get_currency_precision, unit: @publication.get_currency_unit, delimiter: "." %>
    </p>
    <% end %>
    <% unless @publication.city.nil? %>
      <p>
        <i class="fa fa-map-marker"></i>
        Publicación ubicada en
        <%= @publication.city.name %> - <%= @publication.city.department.name %>
      </p>
    <% end %>
    <% if @publication.subject == Publication::PRODUCTOS %>
    <% if @publication.shipping %>
    <p>
      <b>Envío: </b>
    </p>
    <p>
      <%= @publication.get_shipping %>
    </p>
    <% end %>
    <% if @publication.warranty %>
    <p>
      <b>Garantía: </b>
    </p>
    <p>
      <%= @publication.warranty_description %>
    </p>
    <% end %>
    <% end %>
    <% if @publication.subject == Publication::VEHICULOS %>
    <p>
      <b>Año: </b> <%= @publication.year %>
    </p>
    <p>
      <b>Marca: </b> <%= @publication.brand %>
    </p>
    <p>
      <b>Kilómetros: </b> <%= number_with_delimiter(@publication.km, delimiter: ".") %>
    </p>
    <p>
      <b>Modelo: </b> <%= @publication.model %> - <%= number_with_delimiter(@publication.cylinder, delimiter: ".") %> CC
    </p>
    <p>
      <b>Características: </b> <%= @publication.transmission %> - <%= @publication.fuel_type %> - Color <%= @publication.color %>
    </p>
    <% end %>
    <% if @publication.subject == Publication::INMUEBLES %>
      <% if !@publication.total_mtr.nil? &&  @publication.total_mtr > 0 %>
      <p>
        <b>Metros terreno: </b> <%= @publication.total_mtr %>
      </p>
      <% end %>
      <% unless @publication.builded_mtr.blank? %>
      <p>
        <b>Metros construidos: </b> <%= @publication.builded_mtr %>
      </p>
      <% end %>
      <% unless @publication.estrato.blank? %>
      <p>
        <b>Estrato: </b> <%= @publication.estrato %>
      </p>
      <% end %>
      <% unless @publication.admin_price.blank? %>
      <p>
        <b>Administración: </b> <%= number_to_currency @publication.admin_price,  precision: @publication.get_currency_precision, unit: @publication.get_currency_unit %>
      </p>
      <% end %>
    <% end %>
    <% if @publication.subject == Publication::ANIMALES %>

      <% unless @publication.age.blank? %>
      <p>
        <b>Edad: </b> <%= @publication.age %>
      </p>
      <% end %>
    <% end %>
    <div>
      <% if params[:native_app].blank? %>
        <%= render "market/purchases/new", publication: @publication, btn: "btn-lg" %>
        <% if user_signed_in? %>
          <%= link_to mark_as_favorite_market_publication_path(@publication), class: "btn btn-link btn-lg", method: :post do %>

            <% if @is_favorite %>
              <i class="fa fa-heart fa-2x"></i>
            <% else %>
              <i class="fa fa-heart-o fa-2x"></i>
            <% end %>
          <% end %>
        <% else %>
          <button type="button" class="btn btn-link btn-lg" data-toggle="modal" data-target="#subscribe-modal">
            <i class="fa fa-heart-o fa-2x"></i>
          </button>
        <% end %>
      <% end %>
    </div>
    <p style="margin-top: 20px;">
      <i class="fa fa-trophy"></i> Sumas <%= number_with_delimiter(@publication.get_points, delimiter: ".") %> PuntosAgro
    </p>
    <p>
      Recibes tus puntos cuando te califiquen por la compra y califiques la venta
    </p>
    <div>
      Comparte esta publicación en redes:
      <br>
      <%#= social_share_button_tag(@publication.title, :url => market_publication_url(@publication), :image => @publication.get_image("high"), desc: truncate(@publication.description, length: 200), via: "AgroNetoOficial") %>
    </div>
  </div>
</div>

<%= render "market/publications/show/seller_info" %>
<%= render "market/publications/show/description" %>
<%= render "market/publications/show/info_products" %>
<%= render "market/publications/show/info_vehicles" %>
<%= render "market/publications/show/info_services" %>
<%= render "market/publications/show/info_animals" %>
<%= render "market/publications/show/questions", publication: @publication %>

<div class="row visible-md visible-lg" style="margin-top: 40px;">
  <div class="col-md-8 col-md-offset-2">
    <h2 class="green text-center">
      Más publicaciones de vendedor
    </h2>
    <hr>
  </div>
  <div class="col-md-12">
    <%= render "account/users/publications" %>
  </div>
</div>